// components/header/index.js
Component({
    properties:{
        title:{
            type:String,
            value:'默认标题'
        },
        isMore:{
            type:Boolean,
            value:true
        }
    },
    methods:{
        //点击更多发射事件
        handleClick(){
            this.triggerEvent("moreClick")
        }
    }
})